Adjust variable name

diff --git a/scripts/wallpaper-rotater-daemon b/scripts/wallpaper-rotater-daemon
--- a/scripts/wallpaper-rotater-daemon
+++ b/scripts/wallpaper-rotater-daemon
@@ -42,8 +42,8 @@ while true; do
         new_image="${image_list}";
     elif [ "${random_mode}" -eq 1 ]; then
        while true; do
-            index=$(($(cat /dev/urandom | tr -dc '0-9' | head -c5 | sed 's/^0*//') % num_images + 1));
-            new_image=$(echo "${image_list}" | sed -n "${index}p");
+            new_index=$(($(cat /dev/urandom | tr -dc '0-9' | head -c5 | sed 's/^0*//') % num_images + 1));
+            new_image=$(echo "${image_list}" | sed -n "${new_index}p");
             [ "${cur_image}" != "file://${new_image}" ] && break;
         done
     else
@@ -57,7 +57,7 @@ while true; do
     fi
 
     if ! gsettings set org.gnome.desktop.background picture-uri "file://${new_image}" 2>/dev/null; then
-        echo "Could not change the wallpaper to ${new_image}" >&2;
+        echo "Could not change the wallpaper to '${new_image}'" >&2;
         exit 6;
     fi
 done
